-- `tags.emoji` becomes `tags.mark` — one slot in front of a tag's name, holding either a
-- glyph or a colour.

-- The column arrived one migration ago holding emoji and nothing else, and the name said
-- so. Beside it, unrelated, the desktop app painted a colour dot on any tag whose name
-- began with a colour word: `blue_hair` got a blue dot from a list of colour words in
-- code (`COLOR_NAMES`), matched longest-first off the front of the name.
--
-- That guess was wrong often enough to be a nuisance and could never be corrected. It
-- read `gold_trim` as gold and `golden_retriever` as gold too; it painted nothing for a
-- colour the list had never heard of; and a board that wanted a dot on a tag whose name
-- was not a colour word had no way to ask for one. A list in this repo about someone
-- else's vocabulary is the same mistake the emoji table was, one level down.
--
-- So the guess is gone and the column is the answer to both questions. A row holds one
-- value:
--
--   '🎀'       drawn as text, in front of the name
--   '#7fc8ff'  drawn as a dot
--   'blue'     drawn as a dot — any CSS colour name
--   null       nothing, which is still most tags
--
-- One value, not one of each: a tag that wants a dot and a glyph is a tag wanting two
-- marks in the space of one, and the second is read before the name it is attached to.
-- What the value means is decided by looking at it (`markColor` in @common/tags), and
-- what may be written is `readTagMark`'s business in @common/data/tags.
--
-- A rename rather than a new column and a backfill: every value already in there is an
-- emoji, every emoji is still valid under the wider rule, and a rename keeps them without
-- a data migration that could half-finish. Nothing derived a dot from this column before,
-- so nothing on the board changes until somebody types a colour into one.
alter table public.tags rename column emoji to mark;
