-- `tags.category2` goes, replaced by the form groups in the migration beside this one.
--
-- It divided a category into fixed blocks — "dress color", "underwear" — which made
-- Clothes readable and did nothing at all for Character, the category that needed it
-- most. A subgroup was drawn whether or not it could apply, so a board following four
-- series showed all four casts at once and the heading only said which was which. What
-- was actually wanted was fewer names on screen, not the same names under labels.
--
-- A form group answers that: its members are hidden until the tag they hang off is on the
-- post. Everything `category2` could say, a group can say by hanging off the category's
-- own broad tag — and the reverse is not true, which is why this is a replacement and not
-- a second option.
--
-- The column was cosmetic and local: only the desktop picker and the desktop Tags screen
-- ever read it, nothing about search, storage or a post's page knew it existed, and no
-- other column references it. Dropping it costs the headings and nothing else.
alter table public.tags drop column category2;
